document.writeln("<div class=\'footer container\'>");
document.writeln("        <div class=\'footer_frame\'>");
document.writeln("            <div class=\'footer_col_marketing\'>");
document.writeln("                <a href=\'index.html\'><img src=\'img/logo.png\' alt=\'LOGO\' ></a>");
document.writeln("                <div class=\'icons\'>");
document.writeln("                    <a href=\'https://www.facebook.com/\'><i class=\'fab fa-facebook-square\'></i></a>");
document.writeln("                    <a href=\'https://www.instagram.com/\'><i class=\'fab fa-instagram-square\'></i></a>");
document.writeln("                    <a href=\'https://twitter.com/?lang=zh-Hant\'><i class=\'fab fa-twitter-square\'></i></a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer_col_products\'>");
document.writeln("                <div class=\'item\'>");
document.writeln("                    <h4><a>OUR PRODUCTS</a></h4>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'instant_noodles.html\'><i class=\'fas fa-location-arrow\'></i>INSTANT NOODLES</a></li>");
document.writeln("                        <li><a href=\'#\'><i class=\'fas fa-location-arrow\'></i>PHO RICE NOODLES</a></li>");
document.writeln("                        <li><a href=\'#\'><i class=\'fas fa-location-arrow\'></i>BOWL CUP TRAY</a></li>");
document.writeln("                        <li><a href=\'#\'><i class=\'fas fa-location-arrow\'></i>VERMICELLI</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'item\'>");
document.writeln("                    <h4><a href=\'culinary.html\'>CULINARY WORLD</a></h4>");
document.writeln("                </div>");
document.writeln("                <div class=\'item\'>");
document.writeln("                    <h4><a href=\'#\'>MAGIC NOODLE</a></h4>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'#\'><i class=\'fas fa-location-arrow\'></i>INGREDIENTS &<br> &emsp;NUTRITION FACTS</a></li>");
document.writeln("                        <li><a href=\'production.html\'><i class=\'fas fa-location-arrow\'></i>PRODUCTION PROCESS</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                ");
document.writeln("                <div class=\'item\'>");
document.writeln("                    <h4><a href=\'#\'>KNOW MORE ABOUT US</a></h4>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'#\'><i class=\'fas fa-location-arrow\'></i>BRANCHES</a></li>");
document.writeln("                        <li><a href=\'#\'><i class=\'fas fa-location-arrow\'></i>VISIT OUR FACTORY</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln('<div class="copyright">');
document.writeln('            This website is a study project of a student from front-end design engineer class of Weiyu TibaMe Educational Institution. This platform is for learning purposes only. This platform is not for commercial use. If you have concerns about infringement, you can contact with TibaMe and the follow-up will be handled by a dedicated person.<br>Trang wed này là tác phẩm chuyền đề của học sinh “Lớp kĩ sư thiết kế trường Vĩ Dục TibaMe”, trang này chỉ dành cho mục đích học tập, triển lãm.');
document.writeln('Nếu có bất kì thắc mắc vi phạm quyền lợi, bạn có thể nhắn tin riêng cho “Lớp đào tạo kĩ sư thiết kế-TibaMe”, sau đó sẽ có chuyên gia hỗ trợ xử lý');
document.writeln('        </div>');
document.writeln("    </div>");
document.writeln("    <div class=\'copyright_bottom\'>");
document.writeln("        <p>copyright&copy; 2021</p>");
document.writeln("    </div>");