document.writeln("<input type=\'checkbox\' id=\'menu_control\'>");
document.writeln("    <div class=\'main_header\'>");
document.writeln("        <div class=\'header\'>");
document.writeln("            <h1 class=\'logo\'>");
document.writeln("                <a href=\'index.html\'><img src=\'img/logo.png\' alt=\'logo\'></a>");
document.writeln("            </h1>");
document.writeln("            <div class=\'links\'>");
document.writeln("                <div class=\'search_bar\'>");
document.writeln("                    <input class=\'search_section\' type=\'text\' placeholder=\'find your love here!\' id=\'searchSection\'>");
document.writeln("                    <button class=\'search_btn\'><i class=\'fa fa-search\'></i></button>");
document.writeln("                </div>");
document.writeln("                <ul>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'index.html\'><img src=\'img/icon/home.png\' alt=\'home\' id=\'home\'>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'><img src=\'img/icon/login.png\' alt=\'login\' id=\'login\'>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'><img src=\'img/icon/heart.png\' alt=\'fovorite list\' class=\'fovoriteList\'>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'><img src=\'img/icon/cart.png\' alt=\'shopping cart\' class=\'cart\'>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("                <label for=\'menu_control\' class=\'menu_btn\' id=\'menu_btn\'>");
document.writeln("                        <span>menu</span>");
document.writeln("                </label>");
document.writeln("                <select name=\'lang\' id=\'lang_size\'>");
document.writeln("                    <option>Languages</option>");
document.writeln("                    <option value=\'English\'>English</option>");
document.writeln("                    <option value=\'Tiếng Việt\'>Tiếng Việt</option>");
document.writeln("                    <option value=\'bahasa indonesia\'>Bahasa Indonesia</option>");
document.writeln("                    <option value=\'mandarin\'>繁體中文</option>");
document.writeln("                </select>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <ul class=\'main_nav\' id=\'mainNav\'>");
document.writeln("            <li><a>OUR PRODUCTS</a>");
document.writeln("                <ul>");
document.writeln("                    <li><a href=\'instant_noodles.html\'>INSTANT NOODLES</a></li>");
document.writeln("                    <li><a href=\'#\'>PHO RICE NOODLES</a></li>");
document.writeln("                    <li><a href=\'#\'>BOWL CUP TRAY</a></li>");
document.writeln("                    <li><a href=\'#\'>VERMICELLI</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li><a href=\'culinary.html\'>CULINARY WORLD</a></li>");
document.writeln("            <li><a href=\'#\'>MAGIC NOODLE</a>");
document.writeln("                <ul>");
document.writeln("                    <li><a href=\'#\'>INGREDIENTS &<br> NUTRITION FACTS</a></li>");
document.writeln("                    <li><a href=\'production.html\'>PRODUCTION PROCESS</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li><a href=\'#\'>MORE ABOUT US</a>");
document.writeln("                <ul>");
document.writeln("                    <li><a href=\'#\'>BRANCHES</a></li>");
document.writeln("                    <li><a href=\'#\'>VISIT OUR FACTORY</a></li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");