document.writeln('<input type="checkbox" id="menu_control">');
document.writeln('    <div class="main_header">');
document.writeln('        <div class="header">');
document.writeln('            <h1 class="logo">');
document.writeln('                <a href="index.html"><img src="img/logo.png" alt="logo"></a>');
document.writeln('            </h1>');
document.writeln('            <div class="links">');
document.writeln('                <div class="search_bar">');
document.writeln('                    <input class="search_section" type="input" placeholder="find your love here!"');
document.writeln('                    <button class="search_btn"><i class="fa fa-search"></i></button>');
document.writeln('                </div>');
document.writeln('                <ul>');
document.writeln('                    <li>');
document.writeln('                        <a href="index.html"><img src="img/icon/home.png" alt="home"');
document.writeln('                        </a>');
document.writeln('                    </li>');
document.writeln('                    <li>');
document.writeln('                        <a href="#"><img src="img/icon/login.png" alt="login"');
document.writeln('                        </a>');
document.writeln('                    </li>');
document.writeln('                    <li>');
document.writeln('                        <a href="#"><img src="img/icon/heart.png" alt="fovorite list"');
document.writeln('                        </a>');
document.writeln('                    </li>');
document.writeln('                    <li>');
document.writeln('                        <a href="#"><img src="img/icon/cart.png" alt="shopping cart"');
document.writeln('                        </a>');
document.writeln('                    </li>');
document.writeln('                </ul>');
document.writeln('                <label for="menu_control" class="menu_btn" id="menu_btn">');
document.writeln('                        <span>menu</span>');
document.writeln('                </label>');
document.writeln('            </div>');
document.writeln('        </div>');
document.writeln('        <ul class="main_nav">');
document.writeln('            <li><a>OUR PRODUCTS</a>');
document.writeln('                <ul>');
document.writeln('                    <li><a href="instant_noodles.html">INSTANT NOODLES</a></li>');
document.writeln('                    <li><a href="#">PHO RICE NOODLES</a></li>');
document.writeln('                    <li><a href="#">BOWL CUP TRAY</a></li>');
document.writeln('                    <li><a href="#">VERMICELLI</a></li>');
document.writeln('                </ul>');
document.writeln('            </li>');
document.writeln('            <li><a href="culinary.html">CULINARY WORLD</a></li>');
document.writeln('            <li><a href="#">MAGIC NOODLE</a>');
document.writeln('                <ul>');
document.writeln('                    <li><a href="#">INGREDIENTS &<br> NUTRITION FACTS</a></li>');
document.writeln('                    <li><a href="#">PRODUCTION PROCESS</a></li>');
document.writeln('                </ul>');
document.writeln('            </li>');
document.writeln('            <li><a href="#">KNOW MORE ABOUT US</a>');
document.writeln('                <ul>');
document.writeln('                    <li><a href="#">BRANCHES</a></li>');
document.writeln('                    <li><a href="#">VISIT OUR FACTORY</a></li>');
document.writeln('                </ul>');
document.writeln('            </li>');
document.writeln('        </ul>');
document.writeln('    </div>');
document.writeln('');
